        <main id="main">
			<!-- ======= Breadcrumbs ======= -->
            <div class="content-registro">
                <section id="breadcrumbs" class="breadcrumbs registro-section">
                    <form class="row g-3">
                        <div class="col-md-4 campo04">
                            <label for="inputNombres" class="form-label">Nombres</label>
                            <input name="inputNombres" type="text" class="form-control" id="inputNombres" required>
                        </div>
                        <div class="col-md-4 campo04">
                            <label for="inputApellidos" class="form-label">Apellidos</label>
                            <input name="inputApellidos" type="text" class="form-control" id="inputApellidos" required>
                        </div>
                        <div class="col-md-4 campo04">
                            <label for="inputNacionalidad" class="form-label">Nacionalidad</label>
                            <input name="inputNacionalidad" type="text" class="form-control" id="inputNacionalidad" required>
                        </div>
                        <div class="col-md-4 campo04">
                            <label for="inputUsuario" class="form-label">Usuario</label>
                            <span class="input-group-text">
                                <i class="fas fa-user inputUsuario"></i>
                                <input name="inputUsuario" type="text" class="form-control" id="inputUsuario" required>
                            </span>
                        </div>
                        <div class="col-md-4 campo04">
                            <label for="inputEmail01" class="form-label">Email</label>
                            <span class="input-group-text">
                                <i class="fas fa-at inputUsuario"></i>
                                <input name="inputEmail01" type="email" class="form-control" id="inputEmail01" required>
                            </span>
                        </div>
                        <div class="col-md-4 campo04">
                            <label for="inputEmail02" class="form-label">Confirme Email</label>
                            <span class="input-group-text">
                                <i class="fas fa-at inputUsuario"></i>
                                <input name="inputEmail02" type="email" class="form-control" id="inputEmail02" required>
                            </span>
                        </div>
                        <div class="col-md-6">
                            <label for="inputPassword01" class="form-label">Contraseña</label>
                            <span class="input-group-text">
                                <i class="fas fa-key inputUsuario"></i>
                                <input name="inputPassword01" type="password" class="form-control" id="inputPassword01" required>
                            </span>
                        </div>
                        <div class="col-md-6">
                            <label for="inputPassword02" class="form-label">Confirme Contraseña</label>
                            <span class="input-group-text">
                                <i class="fas fa-key inputUsuario"></i>
                                <input name="inputPassword02" type="password" class="form-control" id="inputPassword02" required>
                            </span>
                        </div>
                        <div class="col-md-4 campo04">
                            <label for="inputDireccion01" class="form-label">Dirección</label>
                            <input name="inputDireccion01" type="text" class="form-control" id="inputDireccion01" required>
                        </div>
                        <div class="col-md-4 campo04">
                            <label for="inputComuna" class="form-label">Comuna</label>
                            <span class="input-group-text oculto">
                                <select id="inputComuna" class="form-select select-box">
                                    <option selected>Seleccione su Comuna...</option>
                                    <option>...</option>
                                </select>
                            <span>
                        </div>
                        <div class="col-md-4 campo04">
                            <label for="inputCiudad" class="form-label">Ciudad</label>
                            <span class="input-group-text oculto">
                                <select id="inputCiudad" class="form-select select-box">
                                    <option selected>Seleccione su Ciudad...</option>
                                    <option>...</option>
                                </select>
                            <span>
                        </div>
                        <div class="col-12 div-btn-registro">
                            <button type="submit" class="btn btn-primary btn-registro">Registro</button>
                        </div>
                    </form>
                </section>
            </div>
		</main><!-- End #main -->