<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta content="width=device-width, initial-scale=1.0" name="viewport">
		<title><?php echo $this->titulo; ?></title>
		<meta content="" name="description">
		<meta content="" name="keywords">
		<!-- Favicons -->
		<link href="<?php echo IMG; ?>favicon.png" rel="icon">
		<link href="<?php echo IMG; ?>apple-touch-icon.png" rel="apple-touch-icon">
		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
		<!-- Vendor CSS Files -->
		<link href="<?php echo VDO; ?>bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="<?php echo VDO; ?>icofont/icofont.min.css" rel="stylesheet">
		<link href="<?php echo VDO; ?>boxicons/css/boxicons.min.css" rel="stylesheet">
		<link href="<?php echo VDO; ?>remixicon/remixicon.css" rel="stylesheet">
		<link href="<?php echo VDO; ?>venobox/venobox.css" rel="stylesheet">
		<link href="<?php echo VDO; ?>owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
		<link href="<?php echo VDO; ?>aos/aos.css" rel="stylesheet">
		<!-- Template Main CSS File -->
		<link href="<?php echo CSS; ?>style.css" rel="stylesheet">
		<link href="<?php echo CSS; ?>styles.css" rel="stylesheet">
		<?php
			if (isset($this->controlador)){ ?>
	<link href="<?php echo CSS . $this->controlador; ?>/<?php echo $this->controlador; ?>_styles.css" rel="stylesheet">
		<?php
			}
		?>
		<!-- =======================================================
		* Template Name: Arsha - v2.3.1
		* Template URL: https://bootstrapmade.com/arsha-free-bootstrap-html-template-corporate/
		* Author: BootstrapMade.com
		* License: https://bootstrapmade.com/license/
		======================================================== -->
	</head>
	<body>
		<!-- ======= Header ======= -->
		<header id="header" class="fixed-top header-inner-pages">
			<div class="container d-flex align-items-center">
				<h1 class="logo mr-auto"><a href="index.html"><?php echo $this->titulo; ?></a></h1>
				<!-- Uncomment below if you prefer to use an image logo -->
				<!-- <a href="index.html" class="logo mr-auto"><img src="<?php echo IMG; ?>logo.png" alt="" class="img-fluid"></a>-->
				<nav class="nav-menu d-none d-lg-block">
					<ul>
						<li><a href="index">Home</a></li>
						<li><a href="catalogo">Catálogo</a></li>
						<li><a href="contacto">Contacto</a></li>
						<li><a href="registro">Registro</a></li>
						<li><a href="administracion">Administración</a></li>
					</ul>
				</nav><!-- .nav-menu -->
				<a href="login" class="get-started-btn scrollto">Inicio Sesión</a>
			</div>
		</header><!-- End Header -->