
            <main id="main">
                <div class="content">
                    <div id="login-frm" class="container">
                        <div class="login-container">
                            <div id="output"></div>
                            <div class="avatar"><i id="login-avatar" class="fas fa-user-circle"></i></div>
                            <div class="form-box">
                                <form action="" method="">
                                    <input name="user" type="text" placeholder="username">
                                    <input type="password" placeholder="password">
                                    <button id="btn-login" class="btn btn-info btn-block login" type="submit">Login</button>
                                </form>
                            </div>
                        </div>  
                    </div>
                </div>
            <main>