
            <main id="main">
                <div class="content-contacto">
                    <div class="mb-3 row">
                        <label for="contactoFormName" class="col-sm-2 col-form-label">Nombre:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="contactoFormName" placeholder="Nombre Completo">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="contactoFormEmail" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control" id="contactoFormEmail" placeholder="correo@dominio.com">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="contactoFormFono" class="col-sm-2 col-form-label">Teléfono:</label>
                        <div class="col-sm-10">
                            <input name="contactoFormFono" type="text" class="form-control" id="contactoFormFono" placeholder="+56 X XXXX XXXX">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="contactoFormAsunto" class="col-sm-2 col-form-label">Asunto:</label>
                        <div class="col-sm-10">
                            <input name="contactoFormAsunto" type="text" class="form-control" id="contactoFormAsunto" placeholder="Consulta.....">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="contactoFormFile" class="col-sm-2 col-form-label">Adjuntar Archivo</label>
                        <div class="col-sm-10">
                            <input name="contactoFormFile" class="form-control form-control-sm" id="contactoFormFile" type="file">
                        </div>
                    </div>
                    <div class="mb-5">
                        <label for="contactoFormMensaje" class="form-label">Envíenos su Consulta</label>
                        <textarea name="contactoFormMensaje" class="form-control" id="contactoFormMensaje" rows="3"></textarea>
                    </div>
                    <div class="d-grid gap-2 col-12 mx-auto">
                        <button id="btn-login" class="btn btn-primary col-12" type="button">Enviar</button>
                    </div>
                </div>
            <main>